# Generated by Django 6.0.5 on 2026-05-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwimPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('import_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('dog_swimming', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'swim place',
                'verbose_name_plural': 'swim places',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='places_swim_categor_cbacde_idx'), models.Index(fields=['-rating'], name='places_swim_rating_f4adb0_idx'), models.Index(fields=['dog_swimming'], name='places_swim_dog_swi_9d70dc_idx')],
            },
        ),
    ]
