# Generated by Django 6.0.5 on 2026-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='swimplace',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
