# Generated by Django 6.0.5 on 2026-05-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_swimplace_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimplace',
            name='accessibility_parking',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='diving',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='entrance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='nudist_beach',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='phone_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='refreshment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='source_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='swimplace',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
